inherit_from: ../.rubocop.yml

Metrics/BlockLength:
  Enabled: false

Style/AsciiComments:
  Enabled: false

# Return values like let()s {}, no return value do…end
Style/BlockDelimiters:
  EnforcedStyle: semantic
